/**************************************************************************
Name: Matthew Sprague
Date: 6/11/2024
Description: The East Coast sales division of a company generates 58 percent of total sales. Based on that percentage, write a program that will predict how much the East Coast division will generate if the company has $8.6 million in sales this year.
*************************************************************************/

#include<iostream>
#include<iomanip>
#include<sstream>
#include<string>

using namespace std;

string formatWithCommas(double value)
{
    ostringstream stream;
    stream << fixed << setprecision(2) << value;
    string number = stream.str();

    size_t decimalPos = number.find('.');
    string wholePart = number.substr(0, decimalPos);
    string fractionalPart = number.substr(decimalPos);

    for (int i = static_cast<int>(wholePart.length()) - 3; i > 0; i -= 3)
    {
        wholePart.insert(i, ",");
    }

    return wholePart + fractionalPart;
}

int main()
{
    double totalSales=8600000; //Total sales in dollars. 
    double salesDivision=0.58; //Percentage of sales generated by salesDivsion. 
    double salesGenerated; //Sales generated by salesDivision. 

    salesGenerated=totalSales*salesDivision; //Calculating sales generated by salesDivision. 

    cout<<"The East Coast sales division will generate $"<<formatWithCommas(salesGenerated)<<" in sales this year."<<endl; //Outputting the result. 

    return 0;
}